Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs14.x
    Architectures:
      - arm64
Resources:
  CatalogBatchSave:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./catalog
      Handler: compiled/handler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CatalogTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /catalog
            Method: POST
      Environment:
        Variables:
          TABLE_NAME: !Ref CatalogTable
    Metadata:
      BuildMethod: makefile


  CatalogTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: TVCatalog
      PrimaryKey:
        Type: String
        Name: "slug"