Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs14.x
    Architectures:
      - arm64
Resources:
  CatalogBatchSave:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./catalog
      Handler: compiled/handler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CatalogDatabase
      Events:
        Api:
          Type: Api
          Properties:
            Path: /catalog
            Method: POST
      Environment:
        Variables:
          TABLE_NAME: !Ref CatalogDatabase
    Metadata:
      BuildMethod: makefile

  CatalogDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: slug
          AttributeType: S
      KeySchema:
        - AttributeName: slug
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST