Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs14.x
    Architectures:
      - arm64
Parameters:
  SecretKeyParameter:
    Type: String
    Default: secret
Resources:
  CatalogBatchSave:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./catalog
      Handler: compiled/handler.handler
      Tracing: Active
      Timeout: 20
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CatalogTable
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          TABLE_NAME: !Ref CatalogTable
          SECRET_KEY: !Ref SecretKeyParameter
    Metadata:
      BuildMethod: makefile


  CatalogTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: TVCatalog
      PrimaryKey:
        Type: String
        Name: "slug"